    <html>
        <head>
            <title>Cupcake projekt</title>
            <link rel="stylesheet" type="text/css" href="stylesheets/header.css">

        </head>
        <body>
           <img src="resources/olskercupcakes.png">

           <div class="navigation-bar">


         <a href="FrontController?target=to&to=home" class="navigation-item" >Home</a>
         <a href="FrontController?target=to&to=login" class="navigation-item" >Login</a>
         <a href="FrontController?target=to&to=signup" class="navigation-item">Sign-up</a>



          </div>
        </body>
